server-name=TeenFounders PvP Arena Server
motd=\u00A76\u00A7lTEENFOUNDERS \u00A7fPvP Arena & Duels
server-port=25565
online-mode=false
gamemode=adventure
difficulty=hard
pvp=true
allow-flight=false
enable-command-block=true
max-players=100
view-distance=8
simulation-distance=6
sync-chunk-writes=false
use-native-transport=true
