server-name=TeenFounders 15-Day Survival Event
motd=\u00A76\u00A7lTEENFOUNDERS \u00A7f15-Day Survival Event Season
server-port=25565
online-mode=false
gamemode=survival
difficulty=normal
pvp=true
allow-flight=false
enable-command-block=true
max-players=100
view-distance=8
simulation-distance=6
sync-chunk-writes=false
use-native-transport=true
