server-name=TeenFounders Network Lobby
motd=\u00A76\u00A7lTEENFOUNDERS \u00A7fLobby Hub
server-port=25565
online-mode=false
prevent-proxy-connections=false
gamemode=adventure
difficulty=peaceful
pvp=false
allow-flight=true
enable-command-block=true
max-players=100
view-distance=8
simulation-distance=6
sync-chunk-writes=false
use-native-transport=true
