server-name=TeenFounders Creative Plot Server
motd=\u00A76\u00A7lTEENFOUNDERS \u00A7fCreative Plot World
server-port=25565
online-mode=false
gamemode=creative
difficulty=peaceful
pvp=false
allow-flight=true
enable-command-block=true
max-players=100
view-distance=8
simulation-distance=6
sync-chunk-writes=false
use-native-transport=true
